package com.example.root.educateappcontrolvisitas.api.service;

import com.google.gson.JsonObject;

import retrofit2.Call;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Query;

public interface formularioPedagogicoClient {
    @POST("serviceweb/api/v1/pedagogicalform/?obj_update")
    @FormUrlEncoded
    Call<Void> guardarFormulario(@Query("username") String username,
                                 @Query("api_key") String api_key,
                                 @Field("visit_number") int visit_number,
                                 @Field("visit") String visit,
                                 @Field("extracurricular") int extracurricular,
                                 @Field("internet") int internet,
                                 @Field("no_prof_capacitados") int no_prof_capacitados,
                                 @Field("minutos_uso") double minutos_uso,
                                 @Field("AI_2doEGB_A") double AI_2doEGB_A,
                                 @Field("AI_3roEGB_A") double AI_3roEGB_A,
                                 @Field("AI_4toEGB_A") double AI_4toEGB_A,
                                 @Field("AI_5toEGB_A") double AI_5toEGB_A,
                                 @Field("AI_6toEGB_A") double AI_6toEGB_A,
                                 @Field("AI_7moEGB_A") double AI_7moEGB_A,
                                 @Field("AI_8voEGB_A") double AI_8voEGB_A,
                                 @Field("AI_9noEGB_A") double AI_9noEGB_A,
                                 @Field("AI_10moEGB_A") double AI_10moEGB_A,
                                 @Field("AI_2doEGB_B") double AI_2doEGB_B,
                                 @Field("AI_3roEGB_B") double AI_3roEGB_B,
                                 @Field("AI_4toEGB_B") double AI_4toEGB_B,
                                 @Field("AI_5toEGB_B") double AI_5toEGB_B,
                                 @Field("AI_6toEGB_B") double AI_6toEGB_B,
                                 @Field("AI_7moEGB_B") double AI_7moEGB_B,
                                 @Field("AI_8voEGB_B") double AI_8voEGB_B,
                                 @Field("AI_9noEGB_B") double AI_9noEGB_B,
                                 @Field("AI_10moEGB_B") double AI_10moEGB_B,
                                 @Field("AI_2doEGB_C") double AI_2doEGB_C,
                                 @Field("AI_3roEGB_C") double AI_3roEGB_C,
                                 @Field("AI_4toEGB_C") double AI_4toEGB_C,
                                 @Field("AI_5toEGB_C") double AI_5toEGB_C,
                                 @Field("AI_6toEGB_C") double AI_6toEGB_C,
                                 @Field("AI_7moEGB_C") double AI_7moEGB_C,
                                 @Field("AI_8voEGB_C") double AI_8voEGB_C,
                                 @Field("AI_9noEGB_C") double AI_9noEGB_C,
                                 @Field("AI_10moEGB_C") double AI_10moEGB_C,
                                 @Field("AI_2doEGB_TOTAL") double AI_2doEGB_TOTAL,
                                 @Field("AI_3roEGB_TOTAL") double AI_3roEGB_TOTAL,
                                 @Field("AI_4toEGB_TOTAL") double AI_4toEGB_TOTAL,
                                 @Field("AI_5toEGB_TOTAL") double AI_5toEGB_TOTAL,
                                 @Field("AI_6toEGB_TOTAL") double AI_6toEGB_TOTAL,
                                 @Field("AI_7moEGB_TOTAL") double AI_7moEGB_TOTAL,
                                 @Field("AI_8voEGB_TOTAL") double AI_8voEGB_TOTAL,
                                 @Field("AI_9noEGB_TOTAL") double AI_9noEGB_TOTAL,
                                 @Field("AI_10moEGB_TOTAL") double AI_10moEGB_TOTAL,
                                 @Field("AI_TOTAL_PROMEDIO_A") double AI_TOTAL_PROMEDIO_A,
                                 @Field("AI_TOTAL_PROMEDIO_B") double AI_TOTAL_PROMEDIO_B,
                                 @Field("AI_TOTAL_PROMEDIO_C") double AI_TOTAL_PROMEDIO_C,
                                 @Field("AI_TOTAL_PROMEDIO_TOTAL") double AI_TOTAL_PROMEDIO_TOTAL,
                                 @Field("AT_2doEGB_LEN") double AT_2doEGB_LEN,
                                 @Field("AT_3roEGB_LEN") double AT_3roEGB_LEN,
                                 @Field("AT_4toEGB_LEN") double AT_4toEGB_LEN,
                                 @Field("AT_5toEGB_LEN") double AT_5toEGB_LEN,
                                 @Field("AT_6toEGB_LEN") double AT_6toEGB_LEN,
                                 @Field("AT_7moEGB_LEN") double AT_7moEGB_LEN,
                                 @Field("AT_8voEGB_LEN") double AT_8voEGB_LEN,
                                 @Field("AT_9noEGB_LEN") double AT_9noEGB_LEN,
                                 @Field("AT_10moEGB_LEN") double AT_10moEGB_LEN,
                                 @Field("AT_2doEGB_MAT") double AT_2doEGB_MAT,
                                 @Field("AT_3roEGB_MAT") double AT_3roEGB_MAT,
                                 @Field("AT_4toEGB_MAT") double AT_4toEGB_MAT,
                                 @Field("AT_5toEGB_MAT") double AT_5toEGB_MAT,
                                 @Field("AT_6toEGB_MAT") double AT_6toEGB_MAT,
                                 @Field("AT_7moEGB_MAT") double AT_7moEGB_MAT,
                                 @Field("AT_8voEGB_MAT") double AT_8voEGB_MAT,
                                 @Field("AT_9noEGB_MAT") double AT_9noEGB_MAT,
                                 @Field("AT_10moEGB_MAT") double AT_10moEGB_MAT,
                                 @Field("AT_TOTAL_PROMEDIO_LEN") double AT_TOTAL_PROMEDIO_LEN,
                                 @Field("AT_TOTAL_PROMEDIO_MAT") double AT_TOTAL_PROMEDIO_MAT,
                                 @Field("LA_2doEGB_LEN") double LA_2doEGB_LEN,
                                 @Field("LA_3roEGB_LEN") double LA_3roEGB_LEN,
                                 @Field("LA_4toEGB_LEN") double LA_4toEGB_LEN,
                                 @Field("LA_5toEGB_LEN") double LA_5toEGB_LEN,
                                 @Field("LA_6toEGB_LEN") double LA_6toEGB_LEN,
                                 @Field("LA_7moEGB_LEN") double LA_7moEGB_LEN,
                                 @Field("LA_8voEGB_LEN") double LA_8voEGB_LEN,
                                 @Field("LA_9noEGB_LEN") double LA_9noEGB_LEN,
                                 @Field("LA_10moEGB_LEN") double LA_10moEGB_LEN,
                                 @Field("LA_2doEGB_MAT") double LA_2doEGB_MAT,
                                 @Field("LA_3roEGB_MAT") double LA_3roEGB_MAT,
                                 @Field("LA_4toEGB_MAT") double LA_4toEGB_MAT,
                                 @Field("LA_5toEGB_MAT") double LA_5toEGB_MAT,
                                 @Field("LA_6toEGB_MAT") double LA_6toEGB_MAT,
                                 @Field("LA_7moEGB_MAT") double LA_7moEGB_MAT,
                                 @Field("LA_8voEGB_MAT") double LA_8voEGB_MAT,
                                 @Field("LA_9noEGB_MAT") double LA_9noEGB_MAT,
                                 @Field("LA_10moEGB_MAT") double LA_10moEGB_MAT,
                                 @Field("LA_TOTAL_PROMEDIO_LEN") double LA_TOTAL_PROMEDIO_LEN,
                                 @Field("LA_TOTAL_PROMEDIO_MAT") double LA_TOTAL_PROMEDIO_MAT,
                                 @Field("PA_2doEGB_MAT") double PA_2doEGB_MAT,
                                 @Field("PA_2doEGB_LEN") double PA_2doEGB_LEN,
                                 @Field("PA_3roEGB_MAT") double PA_3roEGB_MAT,
                                 @Field("PA_3roEGB_LEN") double PA_3roEGB_LEN,
                                 @Field("PA_4toEGB_MAT") double PA_4toEGB_MAT,
                                 @Field("PA_4toEGB_LEN") double PA_4toEGB_LEN,
                                 @Field("PA_5toEGB_MAT") double PA_5toEGB_MAT,
                                 @Field("PA_5toEGB_LEN") double PA_5toEGB_LEN,
                                 @Field("PA_6toEGB_MAT") double PA_6toEGB_MAT,
                                 @Field("PA_6toEGB_LEN") double PA_6toEGB_LEN,
                                 @Field("PA_7moEGB_MAT") double PA_7moEGB_MAT,
                                 @Field("PA_7moEGB_LEN") double PA_7moEGB_LEN,
                                 @Field("PA_8voEGB_MAT") double PA_8voEGB_MAT,
                                 @Field("PA_8voEGB_LEN") double PA_8voEGB_LEN,
                                 @Field("PA_9noEGB_MAT") double PA_9noEGB_MAT,
                                 @Field("PA_9noEGB_LEN") double PA_9noEGB_LEN,
                                 @Field("PA_10moEGB_MAT") double PA_10moEGB_MAT,
                                 @Field("PA_10moEGB_LEN") double PA_10moEGB_LEN,
                                 @Field("PA_TOTAL_PROMEDIO_LEN") double PA_TOTAL_PROMEDIO_LEN,
                                 @Field("PA_TOTAL_PROMEDIO_MAT") double PA_TOTAL_PROMEDIO_MAT,
                                 @Field("action_taken") String action_taken,
                                 @Field("created_by") String created_by,
                                 @Field("updated_by") String updated_by

    );

    @GET("serviceweb/api/v1/pedagogicalform/?format=json")
    Call<JsonObject> obtenerFormularios(@Query("username") String username,
                                        @Query("api_key") String api_key,
                                        @Query("limit") int limit);


}
